"""
Django settings for austindsa project.

Generated by 'django-admin startproject' using Django 4.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import sys
from pathlib import Path
import environ


# To add future settings you will want to update the dev-env.env file for debug builds and then update deployment script to include new ENV variables for production

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = Path(__file__).resolve().parent.parent
BASE_DIR = Path(__file__).resolve().parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

environ.Env.read_env(BASE_DIR / "dev-env.env")
env = environ.Env(
    DEBUG=(bool,False),
    # Demo/dev switch: when on, event publishing returns a placeholder success
    # instead of contacting Zoom / Action Network / Google Calendar. The Railway
    # demo box has stubbed credentials and no Selenium container, so a real
    # publish can only fail there; set DEMO_MODE=1 on that box to show the full
    # happy path. Leave off (default) in production.
    DEMO_MODE=(bool,False),
    ALLOWED_HOSTS=(list,[]),
    CSRF_TRUSTED_ORIGINS=(list,[]),
    # Only used for dev/prod, would need to do more work generally to support non-gmail accounts since we are already tied to gCal
    EMAIL_BACKEND=(str,"django.core.mail.backends.smtp.EmailBackend"),
    EMAIL_HOST=(str,"smtp.gmail.com"),
    EMAIL_PORT=(int,587)
)

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")

# Salt for the Link Tree's privacy-first visitor hash (see tools/LinkTree/tracking.py).
# Defaults to SECRET_KEY; set independently so rotating SECRET_KEY doesn't reset
# same-day visitor-uniqueness continuity.
LINK_TRACKING_SALT = env("LINK_TRACKING_SALT", default=SECRET_KEY)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env("DEBUG")

# When on, event publishing is stubbed (no external services contacted) - see
# the env() default above and tools/tasks.py publishEventJob.
DEMO_MODE = env("DEMO_MODE")

# Background tasks (Huey). The queue lives in its own SQLite file - deliberately
# NOT the Django DB file - so the consumer's queue polling never contends with
# Django's writes. In dev and under tests, "immediate" mode runs tasks inline in
# the calling process (no worker needed; periodic schedules don't fire - run the
# underlying management commands manually). Production (docker-compose) sets
# HUEY_IMMEDIATE=False and runs the `worker` service (`manage.py run_huey`).
HUEY = {
    "huey_class": "huey.SqliteHuey",
    "name": "echo",
    "filename": env("HUEY_DB_PATH", default=str(BASE_DIR / "huey.sqlite3")),
    "immediate": env.bool("HUEY_IMMEDIATE", default=(DEBUG or "test" in sys.argv)),
    # Task state belongs in Django models, not Huey's result store.
    "results": False,
    # One worker on purpose: it serializes future Selenium-driven publishes
    # (one Chrome session at a time) and keeps the box's memory footprint flat.
    "consumer": {"workers": 1},
}

ALLOWED_HOSTS = env("ALLOWED_HOSTS")
CSRF_TRUSTED_ORIGINS = env("CSRF_TRUSTED_ORIGINS")

# Every fronting proxy this app runs behind (nginx-conf/*.conf, Railway's edge)
# terminates TLS and sets X-Forwarded-Proto, so trust it - otherwise
# request.scheme reports "http" and absolute URLs built from the request
# (og:image, og:url) advertise the wrong scheme. Plain runserver sends no
# header and falls back to the actual scheme.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

AUTH_USER_MODEL = "tools.user"

# Without this a direct login (no ?next=) bounces to Django's default
# /accounts/profile/, which doesn't exist here.
LOGIN_REDIRECT_URL = "/"

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "huey.contrib.djhuey",
    "tools"
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # Activates the browser-reported timezone (django_timezone cookie set in
    # base.html) so timestamps render in the member's local time
    "tools.middleware.TimezoneMiddleware",
]

ROOT_URLCONF = "urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "tools/templates/"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "tools.contextProcessors.navigation",
            ],
        },
    },
]

WSGI_APPLICATION = "wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": env.db()
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"

STATICFILES_DIRS = [BASE_DIR / "tools/static/"]
STATIC_ROOT = "/var/www/tools-website/static"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Don't need file logging since docker compose will handle capturing stdout to a file and can then see with docker compose logs
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
}

# Email
# Technically not great to do this cause of circular import but should be fine
# Doing this instead of duplicating secrets in the ENV and the Secrets.json
import tools.SecretManager.SecretManager
EMAIL_BACKEND = env("EMAIL_BACKEND")
EMAIL_HOST = env("EMAIL_HOST")
EMAIL_PORT = env("EMAIL_PORT")
EMAIL_HOST_USER = tools.SecretManager.SecretManager.getWebsiteEmailAccountUserName()
EMAIL_HOST_PASSWORD = tools.SecretManager.SecretManager.getWebsiteEmailAccountPassword()
# Used by django.core.mail senders (e.g. the built-in password-reset emails)
# when no explicit from address is given; without it Django falls back to
# webmaster@localhost.
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
EMAIL_USE_TLS = True
# EMAIL_USE_SSL = True
EMAIL_FAIL_SILENTLY = False 