# Generated by Django 5.1.7 on 2026-06-12 21:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0009_access_requests_and_link_tree_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublishJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.IntegerField()),
                ('status', models.IntegerField(default=0)),
                ('payload', models.JSONField()),
                ('conflicts', models.JSONField(blank=True, default=list)),
                ('errorMessage', models.TextField(blank=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('startedAt', models.DateTimeField(blank=True, default=None, null=True)),
                ('finishedAt', models.DateTimeField(blank=True, default=None, null=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publishJobsCreated', to=settings.AUTH_USER_MODEL)),
                ('delegatedEvent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publishJobs', to='tools.delegatedevents')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publishJobs', to='tools.eventowners')),
                ('postedEvent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publishJobs', to='tools.postedevents')),
            ],
        ),
    ]
