# Generated by Django 5.1.7 on 2026-06-19 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0010_publishjob'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permissionrights',
            options={'default_permissions': (), 'managed': False, 'permissions': (('publishEvent', 'Allowed to publish events'), ('requestDelegatedEvent', 'Allowed to request delegated events'), ('approveDelegatedEvent', 'Allowed to approve delegated events'), ('viewDelegatedEventList', 'Allowed to view delegated events'), ('viewPublishedEventList', 'Allowed to view published events'), ('manageEventOwners', 'Allowed to manage event owners'), ('manageLinkTree', 'Allowed to manage link trees, items, and QR codes'), ('viewLinkMetrics', 'Allowed to view link tree click/scan metrics'), ('approveAccessRequest', 'Allowed to approve or deny any access request'), ('administerResolutions', 'Allowed to administer resolutions (Secretary dashboard)'))},
        ),
        migrations.CreateModel(
            name='Resolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('GENERAL', 'General resolution'), ('PROJECT_COMMITTEE', 'Project committee or campaign'), ('BYLAWS_AMENDMENT', 'Bylaws amendment')], max_length=32)),
                ('text', models.TextField()),
                ('status', models.CharField(choices=[('GATHERING', 'Gathering sign-ons'), ('WITHDRAWN', 'Withdrawn'), ('CLOSED', 'Closed')], default='GATHERING', max_length=16)),
                ('locked', models.BooleanField(default=False)),
                ('lockedTextHash', models.CharField(blank=True, max_length=64)),
                ('lockedAt', models.DateTimeField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('proponent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resolutionsProposed', to=settings.AUTH_USER_MODEL)),
                ('targetMeeting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolutions', to='tools.postedevents')),
            ],
            options={
                'ordering': ['-createdAt'],
            },
        ),
        migrations.CreateModel(
            name='ResolutionSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signedAt', models.DateTimeField(auto_now_add=True)),
                ('textHashAtSigning', models.CharField(max_length=64)),
                ('verified', models.BooleanField(default=False)),
                ('verificationStatus', models.CharField(choices=[('OK', 'Verified member in good standing'), ('NOT_MEMBER', 'Not a member in good standing'), ('EXPIRED', 'Membership has lapsed'), ('WRONG_CHAPTER', 'Not an Austin chapter member'), ('NOT_FOUND', 'No matching record found'), ('MULTIPLE', 'Multiple conflicting records found'), ('MISSING_FIELDS', 'Membership record is missing required fields'), ('API_ERROR', 'Could not reach Action Network')], max_length=20)),
                ('checkedAt', models.DateTimeField()),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resolutionSignatures', to=settings.AUTH_USER_MODEL)),
                ('resolution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='tools.resolution')),
            ],
            options={
                'unique_together': {('resolution', 'member')},
            },
        ),
    ]
