# Generated by Django 5.1.7 on 2026-08-11 01:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0010_publishjob'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permissionrights',
            options={'default_permissions': (), 'managed': False, 'permissions': (('publishEvent', 'Allowed to publish events'), ('requestDelegatedEvent', 'Allowed to request delegated events'), ('approveDelegatedEvent', 'Allowed to approve delegated events'), ('viewDelegatedEventList', 'Allowed to view delegated events'), ('viewPublishedEventList', 'Allowed to view published events'), ('manageEventOwners', 'Allowed to manage event owners'), ('manageLinkTree', 'Allowed to manage link trees, items, and QR codes'), ('viewLinkMetrics', 'Allowed to view link tree click/scan metrics'), ('approveAccessRequest', 'Allowed to approve or deny any access request'), ('viewChapterToolAudit', 'Allowed to view chapter-tool audit details'))},
        ),
        migrations.CreateModel(
            name='ChapterResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('blurb', models.TextField(blank=True, help_text='One or two sentences: what this is and what the chapter uses it for.')),
                ('category', models.IntegerField(choices=[(0, 'Communication'), (1, 'Infrastructure'), (2, 'Finance'), (3, 'Social'), (4, 'Organizing')], default=4)),
                ('accessModel', models.IntegerField(choices=[(0, 'Individual logins'), (1, 'Shared vault login'), (2, 'Service account'), (3, 'Mixed'), (4, 'Unconfirmed')], default=4, help_text="A summary only - the real access story lives on this resource's credential rows.")),
                ('payer', models.IntegerField(choices=[(0, 'Chapter'), (1, 'National'), (2, 'Mixed'), (3, 'Free'), (4, 'Unconfirmed')], default=4)),
                ('annualCost', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('costNote', models.CharField(blank=True, help_text='Seat caps, per-seat pricing, or other budget notes.', max_length=300)),
                ('howToGetAccess', models.TextField(blank=True, help_text="Open-layer instructions, e.g. 'Request below' or 'Ask in #it-committee'.")),
                ('stewardName', models.CharField(blank=True, help_text="Text fallback when the steward has no Echo account yet - most stewards won't at launch.", max_length=200)),
                ('requestable', models.BooleanField(default=False, help_text='Whether members can request access to this resource (M2 front door). Requires a steward.')),
                ('lastReviewed', models.DateField(blank=True, null=True)),
                ('reviewedBy', models.CharField(blank=True, max_length=200)),
                ('delegationTier', models.IntegerField(choices=[(0, 'Green'), (1, 'Yellow'), (2, 'Red'), (3, 'Unclassified')], default=3)),
                ('revocationNote', models.TextField(blank=True, help_text='What revocation or rotation actually costs for this resource.')),
                ('continuityNote', models.TextField(blank=True, help_text='Break-glass / continuity guidance if the steward is unreachable.')),
                ('steward', models.ForeignKey(blank=True, help_text='The named owner of this row, and reviewer for its access requests (M2).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stewardedResources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chapter Resource',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ResourceCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="e.g. 'leadership@ Zoom login #2'.", max_length=200)),
                ('kind', models.IntegerField(choices=[(0, 'Individual login'), (1, 'Vault shared login'), (2, 'Service-account key'), (3, 'API token'), (4, '2FA token')])),
                ('vaultCollection', models.CharField(blank=True, help_text='Vault collection name - the hook for a future read-only drift sync.', max_length=200)),
                ('status', models.IntegerField(choices=[(0, 'Live'), (1, 'Retire candidate'), (2, 'Retired')], default=0)),
                ('note', models.TextField(blank=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='tools.chapterresource')),
            ],
            options={
                'verbose_name': 'Resource Credential',
                'ordering': ['resource__name', 'label'],
            },
        ),
        migrations.CreateModel(
            name='ResourceGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personName', models.CharField(blank=True, max_length=200)),
                ('grantedAt', models.DateTimeField(auto_now_add=True)),
                ('fulfilledAt', models.DateTimeField(blank=True, default=None, null=True)),
                ('revokedAt', models.DateTimeField(blank=True, default=None, null=True)),
                ('grantedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resourceGrantsMade', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resourceGrants', to='tools.accessrequests')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='tools.chapterresource')),
                ('revokedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resourceGrantsRevoked', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resourceGrantsReceived', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Resource Grant',
                'ordering': ['-grantedAt'],
            },
        ),
        migrations.CreateModel(
            name='ResourceHolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personName', models.CharField(help_text='Primary - most holders have no Echo account.', max_length=200)),
                ('how', models.IntegerField(choices=[(0, 'Individual login'), (1, 'Vault collection'), (2, 'Service account')], default=0)),
                ('confirmed', models.BooleanField(default=False, help_text='Unconfirmed holders render as open work, not silence.')),
                ('note', models.TextField(blank=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holders', to='tools.chapterresource')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resourceHolderRows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Resource Holder',
                'ordering': ['resource__name', 'personName'],
            },
        ),
        migrations.CreateModel(
            name='ResourceQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('assignedTo', models.CharField(blank=True, help_text='Free-text name - most assignees have no Echo account.', max_length=200)),
                ('raisedAt', models.DateTimeField(auto_now_add=True)),
                ('resolvedAt', models.DateTimeField(blank=True, default=None, null=True)),
                ('resolution', models.TextField(blank=True)),
                ('resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='tools.chapterresource')),
            ],
            options={
                'verbose_name': 'Resource Question',
                'ordering': ['-raisedAt'],
            },
        ),
        migrations.CreateModel(
            name='ToolAuditReadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('target', models.CharField(help_text="Resource name, 'index', or 'questions'.", max_length=200)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='toolAuditReads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tool Audit Read Log',
                'ordering': ['-at'],
            },
        ),
    ]
