# Generated by Django 5.1.7 on 2026-07-28 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0010_publishjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='delegatedevents',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='postedevents',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
