# Generated by Django 5.1.7 on 2026-06-20 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0011_alter_permissionrights_options_resolution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resolution',
            name='decidedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resolution',
            name='effectiveDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resolution',
            name='exportedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resolution',
            name='slug',
            field=models.SlugField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='resolution',
            name='supersededBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes', to='tools.resolution'),
        ),
        migrations.AddField(
            model_name='resolution',
            name='votesAbstain',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resolution',
            name='votesNo',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resolution',
            name='votesYes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resolution',
            name='kind',
            field=models.CharField(choices=[('GENERAL', 'General resolution'), ('PROJECT_COMMITTEE', 'Project committee or campaign'), ('BYLAWS_AMENDMENT', 'Bylaws amendment'), ('CANDIDATE_ENDORSEMENT', 'Candidate endorsement')], max_length=32),
        ),
        migrations.AlterField(
            model_name='resolution',
            name='status',
            field=models.CharField(choices=[('GATHERING', 'Gathering sign-ons'), ('SCHEDULED', 'On the agenda'), ('ADOPTED', 'Adopted'), ('REJECTED', 'Did not pass'), ('WITHDRAWN', 'Withdrawn'), ('SUPERSEDED', 'Superseded')], default='GATHERING', max_length=16),
        ),
        migrations.CreateModel(
            name='ResolutionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromStatus', models.CharField(blank=True, max_length=16)),
                ('toStatus', models.CharField(max_length=16)),
                ('note', models.TextField(blank=True)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resolutionEvents', to=settings.AUTH_USER_MODEL)),
                ('resolution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='tools.resolution')),
            ],
            options={
                'ordering': ['-at'],
            },
        ),
    ]
