# Generated by Django 5.1.7 on 2026-08-11 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0011_chapter_tools'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapterresource',
            name='accessModel',
            field=models.IntegerField(choices=[(0, 'Your own login'), (1, 'Shared login, handed out from the vault'), (2, 'Automated service account'), (3, 'Mixed - some of both'), (4, 'Not confirmed yet')], default=4, help_text="A summary only - the real access story lives on this resource's credential rows."),
        ),
        migrations.AlterField(
            model_name='resourceholder',
            name='how',
            field=models.IntegerField(choices=[(0, 'Their own login'), (1, 'Shared login from the vault'), (2, 'Through the service account')], default=0),
        ),
    ]
