# Generated by Django 5.1.7 on 2026-06-21 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0012_resolution_decidedat_resolution_effectivedate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resolution',
            name='status',
            field=models.CharField(choices=[('GATHERING', 'Gathering sign-ons'), ('SCHEDULED', 'On the agenda'), ('ADOPTED', 'Adopted'), ('REJECTED', 'Did not pass'), ('WITHDRAWN', 'Withdrawn'), ('SUPERSEDED', 'Superseded'), ('LAPSED', 'Lapsed')], default='GATHERING', max_length=16),
        ),
    ]
