# Generated by Django 5.1.7 on 2026-08-11 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0012_alter_chapterresource_accessmodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.IntegerField(choices=[(0, 'Signs you in through'), (1, 'Runs on')])),
                ('note', models.CharField(blank=True, help_text="Optional qualifier, e.g. 'DNS only' or 'staging as well'. Note that a note on a sign-in edge is shown to every member.", max_length=300)),
                ('dependsOn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependents', to='tools.chapterresource')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='tools.chapterresource')),
            ],
            options={
                'verbose_name': 'Resource Dependency',
                'verbose_name_plural': 'Resource Dependencies',
                'ordering': ['resource__name', 'kind', 'dependsOn__name'],
                'constraints': [models.UniqueConstraint(fields=('resource', 'dependsOn', 'kind'), name='unique_resource_dependency'), models.CheckConstraint(condition=models.Q(('resource', models.F('dependsOn')), _negated=True), name='resource_dependency_not_self')],
            },
        ),
    ]
