# Generated by Django 5.1.7 on 2026-08-11 01:32
#
# Both parent branches ship their own full AlterModelOptions snapshot for
# permissionrights (0011_chapter_tools has viewChapterToolAudit but not
# administerResolutions; 0011_alter_permissionrights_options_resolution_and_more
# has administerResolutions but not viewChapterToolAudit). Migration state is a
# literal replace, not a merge, so whichever branch's AlterModelOptions applies
# last would silently drop the other's permission from the migration-recorded
# state - and Permission.create_permissions() (post_migrate) uses that
# historical migration state, not the live models.py, so the dropped
# permission would never get its Permission row created. This explicit
# AlterModelOptions reconciles the two into the one true combined set.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0011_chapter_tools'),
        ('tools', '0013_alter_resolution_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permissionrights',
            options={
                'default_permissions': (),
                'managed': False,
                'permissions': (
                    ('publishEvent', 'Allowed to publish events'),
                    ('requestDelegatedEvent', 'Allowed to request delegated events'),
                    ('approveDelegatedEvent', 'Allowed to approve delegated events'),
                    ('viewDelegatedEventList', 'Allowed to view delegated events'),
                    ('viewPublishedEventList', 'Allowed to view published events'),
                    ('manageEventOwners', 'Allowed to manage event owners'),
                    ('manageLinkTree', 'Allowed to manage link trees, items, and QR codes'),
                    ('viewLinkMetrics', 'Allowed to view link tree click/scan metrics'),
                    ('approveAccessRequest', 'Allowed to approve or deny any access request'),
                    ('administerResolutions', 'Allowed to administer resolutions (Secretary dashboard)'),
                    ('viewChapterToolAudit', 'Allowed to view chapter-tool audit details'),
                ),
            },
        ),
    ]
