# Generated by Django 5.1.7 on 2026-08-11 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0011_chapter_tools'),
        ('tools', '0013_alter_resolution_status'),
    ]

    operations = [
    ]
