# Generated by Django 5.1.7 on 2026-08-11 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0013_resourcedependency'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapterresource',
            name='accessRequestUrl',
            field=models.URLField(blank=True, help_text="The link that starts an access request TODAY - an external form, a signup page. This is the M1 stopgap and is unrelated to the 'requestable' flag below, which is the M2 in-app front door. Most resources will have this and not that for a while."),
        ),
        migrations.AddField(
            model_name='chapterresource',
            name='siteUrl',
            field=models.URLField(blank=True, help_text='Where this thing actually lives, for somebody who already has access.'),
        ),
    ]
