# Generated by Django 5.1.7 on 2026-08-11 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0014_chapterresource_accessrequesturl_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcedependency',
            name='kind',
            field=models.IntegerField(choices=[(0, 'Signs you in through'), (1, 'Runs on'), (2, 'You reach through')]),
        ),
    ]
