# Generated by Django 5.1.7 on 2026-08-11 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0012_alter_chapterresource_accessmodel_and_more'),
        ('tools', '0014_merge_0011_chapter_tools_0013_alter_resolution_status'),
    ]

    operations = [
    ]
