# Generated by Django 5.1.7 on 2026-08-11 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0015_alter_resourcedependency_kind'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permissionrights',
            options={'default_permissions': (), 'managed': False, 'permissions': (('publishEvent', 'Allowed to publish events'), ('requestDelegatedEvent', 'Allowed to request delegated events'), ('approveDelegatedEvent', 'Allowed to approve delegated events'), ('viewDelegatedEventList', 'Allowed to view delegated events'), ('viewPublishedEventList', 'Allowed to view published events'), ('manageEventOwners', 'Allowed to manage event owners'), ('manageLinkTree', 'Allowed to manage link trees, items, and QR codes'), ('viewLinkMetrics', 'Allowed to view link tree click/scan metrics'), ('approveAccessRequest', 'Allowed to approve or deny any access request'), ('viewChapterToolAudit', 'Allowed to view chapter-tool audit details'), ('viewResourceHolders', 'Allowed to see who holds access to chapter tools'))},
        ),
        migrations.AlterField(
            model_name='chapterresource',
            name='blurb',
            field=models.TextField(blank=True, help_text='One or two sentences: what this is and what the chapter uses it for. Shown to every logged-in member.'),
        ),
        migrations.AlterField(
            model_name='chapterresource',
            name='costNote',
            field=models.CharField(blank=True, help_text='Seat caps, per-seat pricing, or other budget notes. Shown to every logged-in member.', max_length=300),
        ),
        migrations.AlterField(
            model_name='chapterresource',
            name='howToGetAccess',
            field=models.TextField(blank=True, help_text="Open-layer instructions, e.g. 'Request below' or 'Ask in #it-committee'. Shown to every logged-in member."),
        ),
        migrations.AlterField(
            model_name='resourceholder',
            name='note',
            field=models.TextField(blank=True, help_text='Note that this is shown to every holder of the viewResourceHolders permission (organizers), not just the IT committee.'),
        ),
    ]
