# Generated by Django 5.1.7 on 2026-08-11 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0013_resourcedependency'),
        ('tools', '0015_merge_20260810_2135'),
    ]

    operations = [
    ]
