# Generated by Django 5.1.7 on 2026-08-11 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0014_chapterresource_accessrequesturl_and_more'),
        ('tools', '0016_merge_20260811_0713'),
    ]

    operations = [
    ]
