# Generated by Django 5.1.7 on 2026-08-11 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0016_alter_permissionrights_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessrequests',
            name='batchId',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
