# Generated by Django 5.1.7 on 2026-08-11 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0015_alter_resourcedependency_kind'),
        ('tools', '0017_merge_20260811_0902'),
    ]

    operations = [
    ]
