# Generated by Django 5.1.7 on 2026-08-11 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0016_alter_permissionrights_options_and_more'),
        ('tools', '0018_merge_20260811_1000'),
    ]

    operations = [
    ]
