# Generated by Django 5.1.7 on 2026-08-11 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0017_accessrequests_batchid'),
        ('tools', '0020_alter_permissionrights_options'),
    ]

    operations = [
    ]
