# Generated by Django 5.1.7 on 2026-08-11 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0018_alter_permissionrights_options'),
        ('tools', '0021_merge_20260811_1256'),
    ]

    operations = [
    ]
