# Generated by Django 5.1.7 on 2026-08-11 21:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    # 0018 on this branch; the resolutions-demo branch's copy of this same file
    # depends on its own 0023 instead, because that branch also carries the
    # self-service access work and its merge migrations. The FILENAME is
    # deliberately identical on both so the demo database's applied-migration
    # record stays valid - only this dependency line differs.
    #
    # When this branch merges into resolutions-demo, git reports an add/add
    # conflict on this file. Resolve it by keeping the DEMO side (0023): that
    # branch has already applied this migration under this name, and renumbering
    # it there would make Django try to add columns that already exist.
    dependencies = [
        ('tools', '0018_alter_permissionrights_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcecredential',
            name='addedAt',
            field=models.DateField(blank=True, default=None, help_text="When this credential first existed, as far as anybody knows. Leave it empty rather than guessing - empty reads as 'not recorded'.", null=True),
        ),
        migrations.AddField(
            model_name='resourcecredential',
            name='lastRotated',
            field=models.DateField(blank=True, default=None, help_text='The day this secret was last actually changed. Not the day somebody looked at it, and not the day a holder was added or removed - only a new secret counts.', null=True),
        ),
        migrations.AddField(
            model_name='resourceholder',
            name='accessLevel',
            field=models.IntegerField(choices=[(0, 'Ordinary access'), (1, 'Admin'), (2, 'Owner'), (3, 'Primary owner'), (4, 'Not confirmed yet')], default=4, help_text='How much this person can do here, not which door they come through.'),
        ),
        migrations.AlterField(
            model_name='chapterresource',
            name='continuityNote',
            field=models.TextField(blank=True, help_text="How somebody gets in if the steward is unreachable - the break-glass path. Name a second person or a second route, not a hope. Example: 'Recovery codes are in the vault collection; two other committee members can read it.'"),
        ),
        migrations.AlterField(
            model_name='chapterresource',
            name='costNote',
            field=models.CharField(blank=True, help_text="Seat caps, per-seat pricing, or other budget notes. Shown to every logged-in member. Example: 'Five seats on the paid plan; a sixth is $8/month more.'", max_length=300),
        ),
        migrations.AlterField(
            model_name='chapterresource',
            name='lastReviewed',
            field=models.DateField(blank=True, help_text='The day somebody last checked this row against reality - that the holder list is still right, that the people on it can still get in, and that the cost and steward are current. It records a check, not an edit. Rows go stale after 90 days.', null=True),
        ),
        migrations.AlterField(
            model_name='chapterresource',
            name='requestable',
            field=models.BooleanField(default=False, help_text='Whether members can ask for this through Echo itself (M2 front door). Tick it only when all three are true: there is a steward to review the request, the delegation tier is Green or Yellow, and holding it gives somebody no power over other members. Leave it off when access is a shared password that is expensive to change, when the holder could spend money or read member data, or when nobody is ever given this directly - a calendar that Echo writes to is reached through Echo, so the thing to request is Echo.'),
        ),
        migrations.AlterField(
            model_name='chapterresource',
            name='reviewedBy',
            field=models.CharField(blank=True, help_text='Who did that check, so the claim has a name attached to it.', max_length=200),
        ),
        migrations.AlterField(
            model_name='chapterresource',
            name='revocationNote',
            field=models.TextField(blank=True, help_text="What taking access away actually costs here, in the order somebody would have to do it. Write the cost, not the intention. Example: 'One shared password, so removing one person means changing it and telling the other four. Budget 30 minutes.'"),
        ),
        migrations.AlterField(
            model_name='chapterresource',
            name='steward',
            field=models.ForeignKey(blank=True, help_text="The one person answerable for this tool: they keep this row true, they are who to ask when access here is unclear, and they review requests for it. A steward is not the only person with access and does not have to be on the committee - the point is that exactly one name is on the hook, so the question never falls to 'somebody'.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stewardedResources', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='resourcecredential',
            name='note',
            field=models.TextField(blank=True, help_text="Anything a person needs to know before touching this credential. Example: 'Rotating this signs everybody out, so do it after a meeting, not during one.'"),
        ),
        migrations.AlterField(
            model_name='resourceholder',
            name='note',
            field=models.TextField(blank=True, help_text="Shown to every holder of the viewResourceHolders permission (organizers), not just the IT committee - so write it for that audience. Example: 'Added for the newsletter, only needs it until the drive ends.'"),
        ),
    ]
